name: Feature Request
description: Suggest an improvement or new feature for an existing blueprint
title: "[Feature]: "
labels: ["type:feature"]
assignees:
  - berTrindade

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

  - type: dropdown
    id: blueprint
    attributes:
      label: Blueprint
      description: Which blueprint should be enhanced?
      options:
        - apigw-sqs-lambda-dynamodb
        - apigw-lambda-dynamodb
        - apigw-lambda-rds
        - apigw-lambda-aurora
        - apigw-lambda-dynamodb-cognito
        - apigw-lambda-rds-proxy
        - alb-ecs-fargate
        - alb-ecs-fargate-rds
        - eks-cluster
        - eks-argocd
        - apigw-eventbridge-lambda
        - apigw-sns-lambda
        - apigw-lambda-bedrock-rag
        - amplify-cognito-apigw-lambda
        - All blueprints
        - Repository/CI infrastructure
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of feature is this?
      options:
        - New module
        - Module enhancement
        - Security improvement
        - Performance optimization
        - Documentation
        - CI/CD improvement
        - Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently, when I try to... I have to manually..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: "Add a new variable/module that..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: "I also considered..."

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: How would this feature be used?
      render: hcl
      placeholder: |
        module "example" {
          source = "../../modules/new_feature"
          # new configuration...
        }

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this require changes to existing deployments?
      options:
        - "No - backward compatible"
        - "Yes - requires migration"
        - "Unsure"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a PR for this feature
          required: false
